# =========================
# ШРИФТ
# =========================

font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

font_size 12.5
modify_font cell_height 1.15

map ctrl+scroll_up   increase_font_size 1
map ctrl+scroll_down decrease_font_size 1

# =========================
# ОКНО И ПРОЗРАЧНОСТЬ
# =========================
window_padding_width 10
confirm_os_window_close 0

# ==============================
# Catppuccin Mocha (Red Edition)
# ==============================

# Основной фон и цвет текста
background            #1e1e2e
foreground            #cdd6f4

# Цвет курсора
cursor                #f38ba8
cursor_text_color     #1e1e2e

# Выделение текста
selection_background  #313244
selection_foreground  #cdd6f4

# ANSI цвета
# Black
color0  #45475a
color8  #585b70
# Red
color1  #f38ba8
color9  #f38ba8
# Green
color2  #a6e3a1
color10 #a6e3a1
# Yellow
color3  #f9e2af
color11 #f9e2af
# Blue
color4  #89b4fa
color12 #89b4fa
# Magenta
color5  #f5c2e7
color13 #f5c2e7
# Cyan
color6  #94e2d5
color14 #94e2d5
# White
color7  #bac2de
color15 #a6adc8

# =========================
# ВЫДЕЛЕНИЕ И ПРОКРУТКА
# =========================

scrollback_lines 10000
enable_audio_bell no
visual_bell_duration 0.1

# =========================
# КОПИРОВАНИЕ / ВСТАВКА
# =========================

map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+с copy_to_clipboard
map ctrl+м paste_from_clipboard

map ctrl+shift+c no_op
map ctrl+shift+v no_op

# =========================
# УДОБСТВА
# =========================

copy_on_select yes
mouse_hide_wait 3
focus_follows_mouse yes
detect_urls yes
open_url_with default

# =========================
# ВКЛАДКИ
# =========================

tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #11111b
active_tab_background   #f38ba8
inactive_tab_foreground #cdd6f4
inactive_tab_background #313244

# =========================
# анимированный курсор
# =========================
cursor_trail 3
