# #######################################################################################
# █▀▄▀█ ▄▀█ █ █▄ █   █▀▀ █▀█ █▄ █ █▀▀ █ █▀▀
# █ ▀ █ █▀█ █ █ ▀█   █▄▄ █▄█ █ ▀█ █▀  █ █▄█
# ГЛАВНЫЙ КОНФИГУРАЦИОННЫЙ ФАЙЛ: СОБИРАЕТ ВСЕ МОДУЛИ ВОЕДИНО
# #######################################################################################

# Подключение цветовой схемы Catppuccin Mocha
source = ~/.config/hypr/mocha.conf

# Подключение переменных окружения и настроек монитора
source = ~/.config/hypr/conf/env.conf

# Подключение настроек внешнего вида (окна, отступы, эффекты)
source = ~/.config/hypr/conf/visuals.conf

# Подключение настроек ввода (клавиатура, мышь, жесты)
source = ~/.config/hypr/conf/input.conf

# Подключение горячих клавиш и управления
source = ~/.config/hypr/conf/binds.conf

# Подключение списка автозапускаемых приложений и скриптов
source = ~/.config/hypr/conf/autostart.conf
