# #######################################################################################
# ▄▀█ █ █ ▀█▀ █▀█ █▀ ▀█▀ ▄▀█ █▀█ ▀█▀
# █▀█ █▄█  █  █▄█ ▄█  █  █▀█ █▀▄  █ 
# ВСЁ, ЧТО СТАРТУЕТ ВМЕСТЕ С СИСТЕМОЙ
# #######################################################################################

# Передача переменных окружения в systemd для работы Wayland
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# Импорт переменных в пользовательскую среду systemctl
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# Легковесный polkit-агент для Hyprland
exec-once = /usr/libexec/hyprpolkitagent
# Запуск верхней панели
exec-once = waybar
# Служба сохранения истории буфера обмена (текст)
exec-once = wl-paste --type text --watch cliphist store 
# Служба сохранения истории буфера обмена (изображения)
exec-once = wl-paste --type image --watch cliphist store
# Индикатор сетевого подключения в трее
exec-once = nm-applet --indicator
# Графический планшет
exec-once = dexptablet
# VPN
exec-once = FlClashX
# Демон анимированных обоев
exec-once = swww-daemon

#АВТОСТАРТ ТЕМЫ 
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'catppuccin-mocha-mauve-standard+default'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
