# #######################################################################################
# █ █ █ █▀ █ █ ▄▀█ █   █▀
# ▀▄▀▄▀ ▄█ █▄█ █▀█ █▄▄ ▄█
# ВНЕШНИЙ ВИД: ГАПСЫ, ГРАНИЦЫ, ПРОЗРАЧНОСТЬ И БЛЮР
# #######################################################################################

general {
    # Внутренние отступы (между окнами)
    gaps_in = 6
    # Внешние отступы (между окном и краем монитора)
    gaps_out = 8
    # Толщина рамки окна
    border_size = 3
    # Цвет рамки активного окна (используем Catppuccin Mauve)
    col.active_border = $mauve $flamingo 45deg
    # Цвет рамки неактивного окна (используем Catppuccin Surface0)
    col.inactive_border = $surface0
    # Алгоритм расположения окон (dwindle — "закручивание")
    layout = dwindle
}

decoration {
    # Скругление углов окон
    rounding = 10
    # Прозрачность активного окна 
    active_opacity = 1
    # Прозрачность неактивных окон
    inactive_opacity = 0.75
    
    blur {
        # Включение размытия под прозрачными окнами
        enabled = true
        # Интенсивность размытия
        size = 8
        # Количество проходов размытия
        passes = 2
        # Размывать фон, игнорируя настройки прозрачности самого окна
        ignore_opacity = true
    }

    shadow {
        # Включение теней у окон
        enabled = true
        # Радиус тени
        range = 4
        # Цвет и прозрачность тени
        color = rgba(1a1a1aee)
    }
}

animations {
    # Включение анимаций
    enabled = yes
    # Настройка кривой Безье
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    # Анимация появления окон
    animation = windows, 1, 7, myBezier
    # Анимация закрытия окон
    animation = windowsOut, 1, 7, default, popin 80%
    # Анимация границ
    animation = border, 1, 10, default
    # Анимация затухания
    animation = fade, 1, 7, default
    # Анимация переключения рабочих столов
    animation = workspaces, 1, 6, default
}

misc {
    # Отключает стандартные обои Hyprland
    disable_hyprland_logo = true
    # Отключает форсирование дефолтных обоев
    force_default_wallpaper = 0
}
